swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1/user
schemes:
  - http
paths:
  /{userId}/transactions:
    post:
      tags:
      - User Transactions
      summary: Transactions
      description: API for user transactions
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: userId
          in: path
          description: user Id
          required: true
          type: string
      responses:
        '200':
          description: Account transactions retrieved successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /{userId}/transactions/{transactionsId}:
    post:
      tags:
      - User Transactions
      summary: Transaction details
      description: API for transactions details
      parameters:
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: string
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /{userId}/transactions/{transactionsId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Transactions API
      description: API for updating a transaction category
      parameters:
        - in: path
          name: TransactionId
          description: Transaction's Id
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction's category
          required: true
          schema:
            $ref: '#/definitions/Category'
      produces:
        - application/json
      responses:
        '200':
          description: Category updated successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      tags:
      - User Transactions
      summary: Transactions API
      description: API for deleting a transaction's category
      produces:
      - application/json
      parameters:
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        description: Transaction's Category
        required: true
        schema: 
          $ref: '#/definitions/Category'
      responses:
        '200':
          description: Category deleted successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
  /{userId}/transactions/{transactionsId}/notes:
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Transactions API
      description: API for updating a transaction Notes
      parameters:
        - in: path
          name: TransactionId
          description: Transaction's Id
          required: true
          type: string
        - in: body
          name: body
          description: Update Transaction's Notes
          required: true
          schema:
            $ref: '#/definitions/Notes'
      produces:
        - application/json
      responses:
        '200':
          description: Notes updated successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      tags:
      - User Transactions
      summary: Transactions API
      description: API for deleting a transaction's Notes
      produces:
      - application/json
      parameters:
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        description: Transaction's Notes
        required: true
        schema: 
          $ref: '#/definitions/Notes'
      responses:
        '200':
          description: Notes deleted successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties: 
          transactionId:
            type: string
          transactionType: 
            type: string
          category:
            type: string
          notes: 
            type: string
  Category:
    type: string
    properties: 
      category: 
        type: string
  Notes:
    type: string
    properties: 
      notes:
        type: string